- hosts: all
  name: Run openstackclient plugin check
  tasks:

    - shell:
        cmd: |
          echo "------------------------------------------------------------"
          virtualenv osc_plugins

    - shell:
        cmd: |
          echo "------------------------------------------------------------"
          osc_plugins/bin/pip install -e src/{{ item.key }}
      when: item.value.required
      with_dict: "{{ zuul.projects }}"

    - shell:
        cmd: |
          echo "------------------------------------------------------------"
          osc_plugins/bin/pip freeze
          echo "------------------------------------------------------------"
          osc_plugins/bin/openstack --version
          osc_plugins/bin/python src/git.openstack.org/openstack/openstackclient/tests/check_osc_commands.py
